create table sys_oper_log
(
    oper_id        bigint auto_increment comment '日志主键'
        primary key,
    title          varchar(50)   default '' null comment '模块标题',
    business_type  int           default 0  null comment '业务类型（0其它 1新增 2修改 3删除）',
    method         varchar(200)  default '' null comment '方法名称',
    request_method varchar(10)   default '' null comment '请求方式',
    operator_type  int           default 0  null comment '操作类别（0其它 1后台用户 2手机端用户）',
    oper_name      varchar(50)   default '' null comment '操作人员',
    dept_name      varchar(50)   default '' null comment '部门名称',
    oper_url       varchar(255)  default '' null comment '请求URL',
    oper_ip        varchar(128)  default '' null comment '主机地址',
    oper_location  varchar(255)  default '' null comment '操作地点',
    oper_param     varchar(2000) default '' null comment '请求参数',
    json_result    varchar(2000) default '' null comment '返回参数',
    status         int           default 0  null comment '操作状态（0正常 1异常）',
    error_msg      varchar(2000) default '' null comment '错误消息',
    oper_time      datetime                 null comment '操作时间',
    cost_time      bigint        default 0  null comment '消耗时间'
)
    comment '操作日志记录';

create index idx_sys_oper_log_bt
    on sys_oper_log (business_type);

create index idx_sys_oper_log_ot
    on sys_oper_log (oper_time);

create index idx_sys_oper_log_s
    on sys_oper_log (status);

INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (100, '菜单管理', 2, 'com.ruoyi.web.controller.system.SysMenuController.edit()', 'PUT', 1, 'admin', '研发部门', '/system/menu', '127.0.0.1', '内网IP', '{"children":[],"component":"medical/index","icon":"guide","isCache":"1","isFrame":"1","menuId":2005,"menuName":"首页","menuType":"C","orderNum":0,"params":{},"parentId":2000,"path":"index","perms":"medical:index:list","routeName":"","status":"0","updateBy":"admin","visible":"0"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-02 13:50:17', 125);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (101, '菜单管理', 2, 'com.ruoyi.web.controller.system.SysMenuController.edit()', 'PUT', 1, 'admin', '研发部门', '/system/menu', '127.0.0.1', '内网IP', '{"children":[],"component":"medical/dashboard/index","icon":"monitor","isCache":"1","isFrame":"1","menuId":2006,"menuName":"数据大屏","menuType":"C","orderNum":1,"params":{},"parentId":2000,"path":"dashboard","perms":"medical:dashboard:list","routeName":"","status":"0","updateBy":"admin","visible":"0"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-02 13:50:50', 50);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (102, '菜单管理', 3, 'com.ruoyi.web.controller.system.SysMenuController.remove()', 'DELETE', 1, 'admin', '研发部门', '/system/menu/4', '127.0.0.1', '内网IP', '4 ', '{"msg":"菜单已分配,不允许删除","code":601}', 0, null, '2026-03-02 13:51:21', 23);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (103, '定时任务', 1, 'com.ruoyi.quartz.controller.SysJobController.add()', 'POST', 1, 'admin', '研发部门', '/monitor/job', '127.0.0.1', '内网IP', '{"concurrent":"1","createBy":"admin","cronExpression":"0 0 2 ? * 1 *","invokeTarget":"ryTask.generateNextWeekSchedule()","jobGroup":"SYSTEM","jobId":100,"jobName":"每周自动创建医生排班计划","misfirePolicy":"1","nextValidTime":"2026-03-08 02:00:00","params":{},"status":"1"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 11:43:46', 72);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (104, '定时任务', 1, 'com.ruoyi.quartz.controller.SysJobController.add()', 'POST', 1, 'admin', '研发部门', '/monitor/job', '127.0.0.1', '内网IP', '{"concurrent":"1","createBy":"admin","cronExpression":"0 0 12 4 3 ? 2026","invokeTarget":"ryTask.generateNextWeekSchedule()","jobGroup":"SYSTEM","jobId":101,"jobName":"自动排班测试","misfirePolicy":"1","nextValidTime":"2026-03-04 12:00:00","params":{},"status":"1"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 11:46:07', 23);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (105, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.changeStatus()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/changeStatus', '127.0.0.1', '内网IP', '{"jobId":101,"misfirePolicy":"0","params":{},"status":"0"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 11:47:12', 39);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (106, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.edit()', 'PUT', 1, 'admin', '研发部门', '/monitor/job', '127.0.0.1', '内网IP', '{"concurrent":"1","createBy":"admin","createTime":"2026-03-04 11:46:07","cronExpression":"0 0,4 12,13 4 3 ? 2026","invokeTarget":"ryTask.generateNextWeekSchedule()","jobGroup":"SYSTEM","jobId":101,"jobName":"自动排班测试","misfirePolicy":"1","nextValidTime":"2026-03-04 13:04:00","params":{},"remark":"","status":"0","updateBy":"admin"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 13:03:29', 62);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (107, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.run()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/run', '127.0.0.1', '内网IP', '{"jobGroup":"SYSTEM","jobId":101,"misfirePolicy":"0","params":{}} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 13:03:34', 15);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (108, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.changeStatus()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/changeStatus', '127.0.0.1', '内网IP', '{"jobId":101,"misfirePolicy":"0","params":{},"status":"1"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 14:57:50', 77);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (109, '定时任务', 1, 'com.ruoyi.quartz.controller.SysJobController.add()', 'POST', 1, 'admin', '研发部门', '/monitor/job', '127.0.0.1', '内网IP', '{"concurrent":"1","createBy":"admin","cronExpression":"0 0 0 * * ?","invokeTarget":"ryTask.checkAppointmentStatus()","jobGroup":"SYSTEM","jobId":102,"jobName":"后台自动更新预约状态","misfirePolicy":"1","nextValidTime":"2026-03-05 00:00:00","params":{},"status":"1"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 14:59:24', 35);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (110, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.run()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/run', '127.0.0.1', '内网IP', '{"jobGroup":"SYSTEM","jobId":102,"misfirePolicy":"0","params":{}} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 14:59:29', 16);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (111, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.run()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/run', '127.0.0.1', '内网IP', '{"jobGroup":"SYSTEM","jobId":102,"misfirePolicy":"0","params":{}} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-04 15:03:58', 67);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (112, '定时任务', 3, 'com.ruoyi.quartz.controller.SysJobController.remove()', 'DELETE', 1, 'admin', '研发部门', '/monitor/job/1,2,3', '127.0.0.1', '内网IP', '[1,2,3] ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-05 10:16:16', 62);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (113, '个人信息', 2, 'com.ruoyi.web.controller.system.SysProfileController.updateProfile()', 'PUT', 1, 'common', '测试部门', '/system/user/profile', '127.0.0.1', '内网IP', '{"admin":false,"avatar":"/src/assets/images/profile.jpg","email":"2070873373@qq.com","nickName":"普通用户","params":{},"phonenumber":"15666666668","sex":"0","userId":2} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-06 11:58:23', 54);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (114, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.edit()', 'PUT', 1, 'admin', '研发部门', '/monitor/job', '127.0.0.1', '内网IP', '{"concurrent":"1","createBy":"admin","createTime":"2026-03-04 11:46:07","cronExpression":"0 25 14 8 3 ? 2026","invokeTarget":"ryTask.generateNextWeekSchedule()","jobGroup":"SYSTEM","jobId":101,"jobName":"自动排班测试","misfirePolicy":"1","nextValidTime":"2026-03-08 14:25:00","params":{},"remark":"","status":"1","updateBy":"admin"} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-08 14:23:49', 54);
INSERT INTO ruoyi_hospital.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (115, '定时任务', 2, 'com.ruoyi.quartz.controller.SysJobController.run()', 'PUT', 1, 'admin', '研发部门', '/monitor/job/run', '127.0.0.1', '内网IP', '{"jobGroup":"SYSTEM","jobId":101,"misfirePolicy":"0","params":{}} ', '{"msg":"操作成功","code":200}', 0, null, '2026-03-08 14:24:19', 11);
