CREATE TABLE medical_department (
    dept_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '科室ID',
    dept_name VARCHAR(50) NOT NULL COMMENT '科室名称',
    dept_code VARCHAR(20) NOT NULL COMMENT '科室编码',
    parent_id BIGINT DEFAULT 0 COMMENT '父科室ID（0为顶级）',
    dept_type TINYINT DEFAULT 1 COMMENT '科室类型：1门诊 2急诊 3住院 4医技',
    location VARCHAR(100) COMMENT '科室位置（如：门诊楼3层）',
    phone VARCHAR(20) COMMENT '科室电话',
    intro TEXT COMMENT '科室简介',
    sort_order INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 0 COMMENT '状态：0正常 1停用',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (dept_id),
    UNIQUE KEY uk_dept_code (dept_code),
    KEY idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科室信息表';
CREATE TABLE medical_doctor (
    doctor_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '医生ID',
    user_id BIGINT COMMENT '关联系统用户ID（RuoYi sys_user）',
    doctor_name VARCHAR(50) NOT NULL COMMENT '医生姓名',
    doctor_code VARCHAR(20) NOT NULL COMMENT '医生工号',
    dept_id BIGINT NOT NULL COMMENT '所属科室ID',
    title VARCHAR(20) COMMENT '职称：主任医师/副主任医师/主治医师/医师',
    specialty VARCHAR(500) COMMENT '擅长领域',
    intro TEXT COMMENT '医生简介',
    avatar VARCHAR(200) COMMENT '头像URL',
    fee DECIMAL(10,2) DEFAULT 0.00 COMMENT '挂号费',
    max_patients INT DEFAULT 20 COMMENT '半日最大接诊数',
    work_status TINYINT DEFAULT 0 COMMENT '工作状态：0在职 1休假 2离职',
    status TINYINT DEFAULT 0 COMMENT '预约状态：0可约 1暂停',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (doctor_id),
    UNIQUE KEY uk_doctor_code (doctor_code),
    KEY idx_dept_id (dept_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生信息表';
CREATE TABLE medical_schedule (
    schedule_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '排班ID',
    doctor_id BIGINT NOT NULL COMMENT '医生ID',
    work_date DATE NOT NULL COMMENT '出诊日期',
    period TINYINT NOT NULL COMMENT '时段：1上午 2下午 3晚间',
    start_time TIME COMMENT '开始时间',
    end_time TIME COMMENT '结束时间',
    total_slots INT NOT NULL DEFAULT 0 COMMENT '总号源数',
    booked_slots INT DEFAULT 0 COMMENT '已预约数',
    slot_minutes INT DEFAULT 30 COMMENT '每个号源时长（分钟）',
    status TINYINT DEFAULT 0 COMMENT '状态：0正常 1停诊 2已满',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (schedule_id),
    UNIQUE KEY uk_doctor_date_period (doctor_id, work_date, period),
    KEY idx_work_date (work_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生排班号源表';
CREATE TABLE medical_appointment (
    appointment_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '预约ID',
    appointment_no VARCHAR(32) NOT NULL COMMENT '预约单号（业务唯一）',
    patient_id BIGINT NOT NULL COMMENT '患者ID（关联sys_user）',
    visitor_id BIGINT COMMENT '就诊人ID（0表示本人）',
    doctor_id BIGINT NOT NULL COMMENT '医生ID',
    schedule_id BIGINT NOT NULL COMMENT '排班ID',
    appointment_date DATE NOT NULL COMMENT '预约就诊日期',
    period TINYINT NOT NULL COMMENT '时段',
    time_slot VARCHAR(20) COMMENT '具体时间段（如08:00-08:30）',
    status TINYINT DEFAULT 0 COMMENT '状态：0待支付 1待就诊 2就诊中 3已完成 4已取消 5失约',
    fee DECIMAL(10,2) DEFAULT 0.00 COMMENT '挂号费',
    pay_status TINYINT DEFAULT 0 COMMENT '支付状态：0未支付 1已支付 2已退款',
    pay_time DATETIME COMMENT '支付时间',
    pay_way VARCHAR(20) COMMENT '支付方式：wechat/alipay',
    checkin_time DATETIME COMMENT '签到时间',
    finish_time DATETIME COMMENT '就诊完成时间',
    cancel_time DATETIME COMMENT '取消时间',
    cancel_reason VARCHAR(200) COMMENT '取消原因',
    medical_record_id BIGINT COMMENT '关联病历ID',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (appointment_id),
    UNIQUE KEY uk_appointment_no (appointment_no),
    KEY idx_patient_id (patient_id),
    KEY idx_doctor_date (doctor_id, appointment_date),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='预约订单表';
CREATE TABLE medical_patient_visitor (
    visitor_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '就诊人ID',
    patient_id BIGINT NOT NULL COMMENT '主账户患者ID',
    name VARCHAR(50) NOT NULL COMMENT '姓名',
    id_card VARCHAR(18) NOT NULL COMMENT '身份证号（加密）',
    phone VARCHAR(11) COMMENT '手机号',
    relation VARCHAR(10) COMMENT '与主账户关系：本人/配偶/子女/父母/其他',
    gender TINYINT COMMENT '性别：0男 1女',
    birth_date DATE COMMENT '出生日期',
    medical_card_no VARCHAR(30) COMMENT '医保卡号',
    allergy_history TEXT COMMENT '过敏史',
    past_history TEXT COMMENT '既往病史',
    is_default TINYINT DEFAULT 0 COMMENT '是否默认就诊人：0否 1是',
    status TINYINT DEFAULT 0 COMMENT '状态：0正常 1删除',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (visitor_id),
    KEY idx_patient_id (patient_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='就诊人档案表';